version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: build
    ports:
      - 4000:4000
    command: pnpm run dev

  frontend:
    build:
      context: ./svelte-frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
